server:
  port: 1024
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  jpa:
    show-sql: true
debug: true