package xyz.idiosoul.fair.order.constant;

/**
 * 售后操作
 */
public enum RequestActionEnum {
    BUYER_REFUND, BUYER_RETURN, SELLER_AGREE, SELLER_DISAGREE, BUYER_SHIP, SELLER_RECEIVE, BUYER_APPEAL,BUYER_WITHDRAW, PLAT_SUPPORT_BUYER, PLAT_SUPPORT_SELLER, BUYER_CANCEL, REFUND_SUCCESS, BUYER_EDIT
}
